name: CI\CD_webmail
on:
  schedule:
    - cron: '16 6 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
  deploy:
    environment: stage
    runs-on: ubuntu-latest
    needs: build_and_pub
    
    steps:
      - name: Deploy to own srv via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 92.255.165.42
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script:
            touch /hello_from_github.txt
      
      
      
      
      
      
      
      
      
      
      
      
      
    
